#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html


spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        id.new_generator_mappings: false
  datasource:
    # ImMemory
    url: jdbc:h2:mem:luga
    username: sa
    password:
  h2.console.enabled: true



#            oauth2:
#              client:
#                clientId: xxxxxxx
#                clientSecret: xxxxxxxxxxx
#                accessTokenUri: https://oauth.vk.com/access_token
#                userAuthorizationUri: https://oauth.vk.com/authorize
#                tokenName: code
#                authenticationScheme: query
#                clientAuthenticationScheme: form
#                grant-type: authorization_code
#              resource:
#                userInfoUri: https://api.vk.com/method/users.get